### ISSUE TITLE
Is it possible provide executable code for the evaluation metrics ？

### ISSUE THREAD

**Issue by joyyy111** [tthinking/DATFuse#12]
Thanks to the authors for the code, is it possible to provide executable code for the evaluation metrics mentioned in the paper, e.g. Normalized Mutual Information, Tsallis Entropy, etc.?
![image](https://github.com/user-attachments/assets/b79038f5-5237-4ba2-955a-d568292fd26d)

**Comment by wahaha-debug** [comment]
同问

**Comment by tthinking** [comment]
Please refer to <a style="color: #447ec9; text-decoration:none" onmouseover="this.style.color='#FF0000'" 
          onmouseout="this.style.color='#447ec9'" href="https://github.com/tthinking/MATR/tree/main/evaluation">
          MATR</a>

**Comment by wahaha-debug** [comment]
> Please refer to  请参考[ MATR 马特](https://github.com/tthinking/MATR/tree/main/evaluation)

非常感谢！！！

**Comment by wahaha-debug** [comment]
> Please refer to [ MATR](https://github.com/tthinking/MATR/tree/main/evaluation)

非常感谢！！！
