### ISSUE TITLE
问题请教GetDataset

### ISSUE THREAD

**Issue by YidaMyth** [tthinking/DATFuse#3]
打扰博主，请教一下问题。

输入 GetDataset 中的路径是'...'，对于里面的    
def __getitem__(self, index):
        ir = '...'
        vi = '...'
请问这儿的 ir 和 vi 应该如何获取呢？填什么路径哇。对于GetDataset在 Train 中只分别传入了training_dir_ir和training_dir_vi 如何在GetDataset类中获取 ir 和 vi 图像路径呢？

**Comment by limyoonahh** [comment]
请问你知道了吗

**Comment by quyiting** [comment]
请问解决了吗

**Comment by limyoonahh** [comment]
> > 请问你知道了吗
> 
> 请问您现在解决了吗

没有
