### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'models/.../args.txt'

### ISSUE THREAD

**Issue by jianguo520** [tthinking/DATFuse#6]
Hello author!
Thank you for releasing the code. I am trying to reproduce the experimental results mentioned in your paper, but when I was training , I found that the FileNotFoundError: [Errno 2] No such file or directory: 'models/.../args.txt', I would like to ask you what caused this？
![3556f8340b32a6cdbc2fd3e29507760](https://github.com/tthinking/DATFuse/assets/81084898/4f1a1cb1-dd7e-481c-bee9-8fd9b3a7b15c)

**Comment by tthinking** [comment]
Please check the path.
